[project]
name = "vmpfix"

[options]
ZYDIS_BUILD_TOOLS = false
ZYDIS_BUILD_EXAMPLES = false

[fetch-content.argparse]
git = "https://github.com/p-ranav/argparse.git"
tag = "v2.2"

[fetch-content.linux-pe]
git = "https://github.com/can1357/linux-pe.git"
tag = "ce24224"

[fetch-content.Zydis]
git = "https://github.com/zyantific/zydis.git"
tag = "9fc98de"

[subdir."Blackbone/src/BlackBone"]
cmake-after = """
target_compile_features(BlackBone PUBLIC cxx_std_17)
if(CMAKE_SIZEOF_VOID_P EQUAL 8)
    link_directories(Blackbone/src/3rd_party/DIA/lib/amd64)
elseif(CMAKE_SIZEOF_VOID_P EQUAL 4)
    link_directories(Blackbone/src/3rd_party/DIA/lib)
endif()
target_link_libraries(BlackBone PUBLIC diaguids.lib)
target_include_directories(BlackBone PUBLIC Blackbone/src)
"""

[target.vmpfix]
type = "executable"
sources = [
    "src/*.cpp", 
    "include/*.hpp"
]
include-directories = [
    "include",
]
compile-features = ["cxx_std_20"]
link-libraries = [
    "BlackBone",
    "linux-pe",
    "Zydis",
    "argparse"
]
